version: '3.4'

services:

  # catalog db container with image 
  catalogdb:
    image: mongo:4.2

 # basketdb container with image
  basketdb:
    image: redis:alpine # alpine tag with redis give the redis image that requires less space

 # discountdb container with image
  discountdb:
    image: postgres

 # pgadmin container with image for postgres db management tool
  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

# APIs

  # catalog api container with image  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

    
  # basket api container with image
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  # discount api container with image
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount.API/Discount.API/Dockerfile

 # Grpc container with image
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount.API/Discount.Grpc/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

